name: AWS RDS

on:
  push:
    branches:
      - test3

jobs:
  db-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install PostgreSQL Client
        run: sudo apt-get install postgresql-client -y

      - name: Connect to RDS and Create Database
        env:
          DB_HOST: database-1.cluster-csp0o8k8uf28.us-east-1.rds.amazonaws.com
          DB_USER: psql
          DB_PASSWORD: stockhome
        run: |
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -u $DB_USER -d postgres -c "CREATE TABLE students (id SERIAL PRIMARY KEY, name VARCHAR(100), age INT);"

      - name: Validate Data
        run: |
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -u $DB_USER -d postgres -c "SELECT * FROM students;" 